personnage_index:
    path:     /
    defaults: { _controller: "AppBundle:Personnage:index" }
    methods:  GET

personnage_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Personnage:show" }
    methods:  GET

personnage_new:
    path:     /new
    defaults: { _controller: "AppBundle:Personnage:new" }
    methods:  [GET, POST]

personnage_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Personnage:edit" }
    methods:  [GET, POST]

personnage_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Personnage:delete" }
    methods:  DELETE
