AppBundle\Entity\Personnage:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PersonnageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        xP:
            type: integer
            column: XP
            nullable: true
        forces:
            type: integer
            column: Forces
            nullable: true
        puissanceArme:
            type: integer
            column: PuissanceArme
            nullable: true
        pV:
            type: integer
            column: PV
            nullable: true
    lifecycleCallbacks: {  }
